version: '3'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./team_member_management/.env.db
  web:
    restart: always
    build:
      context: ./team_member_management
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py migrate --settings=team_member_management.settings.production && python manage.py collectstatic --noinput --settings=team_member_management.settings.production && gunicorn team_member_management.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=team_member_management.settings.production -w 4"
    container_name: team_member_service
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/team_member_service
      - ./team_member_management/static:/static
    env_file:
      - ./team_member_management/.env
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./team_member_management/static:/static
volumes:
  postgres_data:
